CLASS zcl_code_dojo_abap_git_ibr DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_code_dojo_abap_git_ibr IMPLEMENTATION.
ENDCLASS.
